pb_url = "http://localhost:8090"
interval_ms = 4000
transition = "fade"
transition_duration_ms = 600
cache_dir = "/tmp/frame-viewer-cache"
cache_size_limit_gb = 2
enable_realtime = true
shuffle = false
fullscreen = false
device_id = "43fsyxpmwp55t86"
device_api_key = "LH0wL8Qe4uRvTe1RrjneoZVs24CqZOyk"
